# Pre-commit configuration for DeclarativeUI
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Pre-commit hooks for general file maintenance
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Remove trailing whitespace
      - id: trailing-whitespace
        exclude: '\.patch$'
      # Ensure files end with newline
      - id: end-of-file-fixer
        exclude: '\.patch$'
      # Check for large files (>500KB)
      - id: check-added-large-files
        args: ["--maxkb=500"]
      # Check for merge conflicts
      - id: check-merge-conflict
      # Check YAML syntax
      - id: check-yaml
        files: \.(yml|yaml)$
      # Check JSON syntax
      - id: check-json
        files: \.json$
      # Check XML syntax
      - id: check-xml
        files: \.xml$
      # Prevent committing to main/master
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "master"]

  # C++ code formatting with clang-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        files: \.(cpp|hpp|cc|cxx|c|h)$
        exclude: |
          (?x)^(
              build/.*|
              .*_autogen/.*|
              .*\.moc$|
              .*moc_.*\.cpp$|
              .*ui_.*\.h$
          )$

  # CMake formatting
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        files: (CMakeLists\.txt|\.cmake)$
        args: [--line-width=100, --tab-size=4]
        additional_dependencies: [PyYAML]
    #  - id: cmake-lint
    #    files: (CMakeLists\.txt|\.cmake)$
    #    args: [--line-width=100]
    #    additional_dependencies: [PyYAML]

  # Python formatting for build scripts (if any)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: \.py$
        language_version: python3

  # For some reason, this hook is not working as expected
  # Markdown formatting and linting
  #- repo: https://github.com/igorshubovych/markdownlint-cli
  #  rev: v0.38.0
  #  hooks:
  #    - id: markdownlint
  #      args: ['--fix']
  #      files: \.md$
  #      exclude: 'CHANGELOG\.md'

# Configuration for different CI environments
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [cppcheck] # Skip cppcheck in CI as it can be slow
  submodules: false
